apiVersion: v1
kind: Service
metadata:
  name: ngi-service
  namespace: nm
spec:
    selector:
      app: nginx
    ports:
      - protocol: TCP
        port: 80
        targetPort: 80
--- 
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: nm
  labels:
    app: nginx
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80

