apiVersion: v1
kind: Pod
metadata:
  name: busybox-pod
spec:
  containers:
    - name: busybox-container
      image: busybox:latest
      command: ["sleep", "3600"]
      # You can add additional commands or arguments if needed

