apiVersion: v1
kind: Pod
metadata:
  name: svc-pod
  namespace: nm2
  labels:
    app: svc-label
spec:
  containers:
    - name: nginx-cont
      image: nginx:latest
      ports:
        - containerPort: 80

    - name: ubuntu-container
      image: ubuntu:latest
      command: ["sleep", "3600"]
      # You can add additional commands or arguments if needed
