apiVersion: v1
kind: Pod
metadata:
  name: pod-tom
  namespace: nm
  labels:
    app: tomcat

spec:
  containers:
    - name: tom
      image: tomcat:latest
      ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  namespace: nm
  
spec:
  type: NodePort
  selector:
    app: tomcat
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  namespace: nm
spec:
  containers:
    - name: ubuntu-container
      image: ubuntu:latest
      command: ["sleep", "3600"]
      # You can add additional commands or arguments if needed

---
apiVersion: v1
kind: Pod
metadata:
  name: centos
  namespace: nm
spec:
  containers:
    - name: cent-container
      image: centos:latest
      command: ["sleep", "3600"]
      # You can add additional commands or arguments if needed



