apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: os  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      namespace: os
      labels:
        app: nginx-app
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
        - name: bastion
          image: ubuntu:latest
          command: ["sleep", "3600"]
      


---
apiVersion: v1
kind: Service
metadata:
  name: service1
  namespace: os  
spec:
  
  selector:
    app: nginx-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

