apiVersion: v1
kind: Pod
metadata: 
  name: tmp-pod2
  namespace: nm1 
  labels:
    app: enginx
spec:
  containers:
    - name: nginx-cont
      image: nginx:latest
      ports:
        - containerPort: 80
