apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replicaset
  namespace: os
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
      namespace: os
    spec:
      containers:
        - name: ubuntu-container
          image: ubuntu:latest
          command: ["sleep", "3600"]
      # You can add additional commands or arguments if needed

        - name: centos-container
          image: centos:latest
          command: ["sleep", "3600"]
      # You can add additional commands or arguments if needed
        - name: nginx-container
          image: nginx:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service-port
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service-cluster
spec:
    selector:
      app: my-app
    ports:
      - protocol: TCP
        port: 80
        targetPort: 80


