apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-rll
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-ap
  template:
    metadata:
      labels:
        app: my-ap
    spec:
      containers:
        - name: nginx
          image: nginx:stable-perl
          ports:
            - containerPort: 80

