apiVersion: v1
kind: Pod
metadata:
  name: tomcat-pod
  namespace: nm
  labels:
    app: tomcat
spec:
  containers:
    - name: tomcat-container
      image: tomcat:latest
      ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: tomcat-pod1
  namespace: nm1
  labels:
    app: tomcat
spec:
  containers:
    - name: tomcat-container
      image: tomcat:latest
      ports:
        - containerPort: 8080

